security:
  enabled: true
  max-concurrent-sessions: 5
  cors:
    allowed:
      origins: http://localhost:9892,http://localhost:4200
      methods: GET,HEAD,POST,PUT,DELETE,OPTIONS
      # Include Upgrade + Connection for the WebSocket HTTP handshake
      headers: "Authorization,content-type,app-called-service,access-token,refresh-token,Upgrade,Connection"
    enabled: true
    path:
      pattern: /**
  jwt:
    issuer: keit
    secret: ${JWT_SECRET:keit_secret}
    expiration: 600 # 10 mins
    expiration-refresh: 900 # 15 mins
  app-validator-filter:
    app-header-name-validation-Filter: true # habilita la validación de cabeceras
    app-header-name: 'app-called-service' # nombre de la cabecera que tiene el identificador
    app-self-name: 'generic-ws' # nombre del módulo que espera recibir
    app-security-name: 'generic-security' # nombre del módulo de seguridad