application:
  name: ${app.name:generic-boot}
  version: ${app.version:0.1.0-SNAPSHOT}
  build: ${app.build:local}
  buildTime: ${app.buildTime:local}

server:
  port: 9891
  timeZone: Europe/Madrid
  servlet:
    context-path: /
    api-path: /api/v1
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-response: true

spring:
  application.name: ${app.name:generic-boot}
  profiles:
    default: dev
  config:
    import:
      - optional:classpath:build.properties
      - application-base.yaml
      - application-flyway.yaml
      - application-security.yaml
      - optional:application-mail.yaml
      - optional:application-${spring.profiles.active}.yaml

logging:
  file:
    path: dist/logs

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when-authorized
      roles: ADMIN
    metrics:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: ${application.name}
    version: ${application.version}
    build: ${application.build}

springdoc:
  api-docs.path: /public/api-docs
  packagesToScan: dev.barrikeit.rest,dev.barrikeit.security.rest
  show-actuator: false
  swagger-ui:
    display-request-duration: true
    filter: true
    operations-sorter: method
    path: /public/swagger-ui
    use-root-path: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json